### ISSUE TITLE
Nullable handler doesn't support objects

### ISSUE THREAD

**Issue by jml** [jml/graphql-api#102]
Probably.

Code is:

```haskell
instance forall m hg. (HasResolver m hg, Functor m, ToValue (Maybe hg)) => HasResolver m (Maybe hg) where
  type Handler m (Maybe hg) = m (Maybe hg)
  resolve handler _ =  map (ok . toValue) handler
```

Note that it discards the selection set. That can't be good.

**Comment by teh** [comment]
Didn't you just remove this code in #101?

**Comment by jml** [comment]
Nope. Removing it broke the tests. Just pushed a revised #101 which restores the code together with a comment that explains what it does and why it's broken.
