### ISSUE TITLE
I try to install with cabal install graphql-api, but I have an issue

### ISSUE THREAD

**Issue by tibastral** [jml/graphql-api#121]
Building library for graphql-api-0.1.2..
[ 1 of 18] Compiling GraphQL.Internal.Arbitrary ( src/GraphQL/Internal/Arbitrary.hs, dist/build/GraphQL/Internal/Arbitrary.o )
[ 2 of 18] Compiling GraphQL.Internal.OrderedMap ( src/GraphQL/Internal/OrderedMap.hs, dist/build/GraphQL/Internal/OrderedMap.o )
[ 3 of 18] Compiling GraphQL.Internal.Syntax.Tokens ( src/GraphQL/Internal/Syntax/Tokens.hs, dist/build/GraphQL/Internal/Syntax/Tokens.o )
[ 4 of 18] Compiling GraphQL.Internal.Syntax.AST ( src/GraphQL/Internal/Syntax/AST.hs, dist/build/GraphQL/Internal/Syntax/AST.o )

src/GraphQL/Internal/Syntax/AST.hs:55:1: warning: [-Wdodgy-imports]
    Module ‘Protolude’ does not export ‘Type’
   |
55 | import Protolude hiding (Type)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 5 of 18] Compiling GraphQL.Internal.Syntax.Parser ( src/GraphQL/Internal/Syntax/Parser.hs, dist/build/GraphQL/Internal/Syntax/Parser.o )

src/GraphQL/Internal/Syntax/Parser.hs:86:23: error:
    Ambiguous occurrence ‘option’
    It could refer to either ‘Protolude.option’,
                             imported from ‘Protolude’ at src/GraphQL/Internal/Syntax/Parser.hs:8:1-41
                             (and originally defined in ‘Data.Semigroup’)
                          or ‘Data.Attoparsec.Text.option’,
                             imported from ‘Data.Attoparsec.Text’ at src/GraphQL/Internal/Syntax/Parser.hs:23:5-10
                             (and originally defined in ‘Data.Attoparsec.Combinator’)
   |
86 | field = AST.Field <$> option empty (pure <$> alias)
   |                       ^^^^^^

src/GraphQL/Internal/Syntax/Parser.hs:333:12: error:
    Ambiguous occurrence ‘option’
    It could refer to either ‘Protolude.option’,
                             imported from ‘Protolude’ at src/GraphQL/Internal/Syntax/Parser.hs:8:1-41
                             (and originally defined in ‘Data.Semigroup’)
                          or ‘Data.Attoparsec.Text.option’,
                             imported from ‘Data.Attoparsec.Text’ at src/GraphQL/Internal/Syntax/Parser.hs:23:5-10
                             (and originally defined in ‘Data.Attoparsec.Combinator’)
    |
333 | optempty = option mempty
    |            ^^^^^^
cabal: Leaving directory '/var/folders/zb/jqp3vqj170nc5vkyw8k2p_tw0000gn/T/cabal-tmp-13818/graphql-api-0.1.2'
cabal: Error: some packages failed to install:
graphql-api-0.1.2-HmKbgdf15yT6zJHN4EkHkp failed during the building phase. The
exception was:
ExitFailure 1

**Comment by jml** [comment]
I think probably we need to put an upper bound on the protolude version (or update the code to use the latest protolude and then put a lower bound on it). 

I personally won't have time to address this over the next few weeks, but would be happy to review a PR.

**Comment by tibastral** [comment]
What version of Protolude is working for you ?

**Comment by jml** [comment]
Whichever is included in the Stackage nightly-2017-01-25 resolver, c.f.
https://github.com/jml/graphql-api/blob/master/stack.yaml#L1

**Comment by teh** [comment]
```$ ghc-pkg list | grep proto
    protolude-0.1.10
``` is working for me, so it's probably protolude 0.2 that breaks

**Comment by teh** [comment]
@tibastral does the latest master (which includes https://github.com/jml/graphql-api/pull/123) work for you?

**Comment by jml** [comment]
@tibastral I'm closing this for now, but please re-open if you're still having issues.
