### ISSUE TITLE
Make a backwards compatible API

### ISSUE THREAD

**Issue by rahulmutt** [jml/graphql-api#125]
Extensions like `TypeApplications` cause problems for other Haskell implementations like [Eta](http://eta-lang.org/). The way around this is to use `Proxy a` arguments when you want to send type arguments to a particular function. 

A good solution that can stay compatible with other Haskell implementations as well is to:
- Add a CPP constant called `HAS_TYPE_APPLICATIONS` that is automatically turned on for GHC 8 via a Cabal conditional.
- All source code uses of type applications should be `#ifdef`'d using the defined constant above.

I'd be happy to take this up if this sounds like a good approach.

**Comment by jml** [comment]
Hi!

> Extensions like `TypeApplications`…

Are there any other extensions that we use that are problematic?

**Comment by rahulmutt** [comment]
Hi @jml, after further investigation, yes there are:

- `TypeInType`
- `TypeFamilyDependencies`

I'm currently trying to see if they're a way to get the same functionality without those extensions.

**Comment by jml** [comment]
Hi @rahulmutt,

@teh and I were chatting today, and decided that we would like graphql-api to be for GHC 8.0.2 and later, and any compilers compatible with those. We rely on a lot of recent type extensions in a pretty fundamental way. We don't intend to change that any time soon.

If you want to do a "friendly fork" that makes a version of graphql-api which works for Eta or GHC 7.x, please feel free. We'll gladly link to it, and will accept PRs that make it easier to maintain (as long as they are consistent with our design principles).

I'm going to close this issue for now. I'm happy to continue discussion here, but we'll only re-open it if @teh and I agree that it's a good idea for this repo to extend our compiler support.

Thanks,
jml
