### ISSUE TITLE
[Feature Request] Prettier (color) printing for the Tasty tests. 

### ISSUE THREAD

**Issue by sunwukonga** [jml/graphql-api#136]
The output of the HSpec tests isn't very inspiring (I much prefer big green OK's or ticks).

From [https://github.com/hspec/hspec/issues/333](https://github.com/hspec/hspec/issues/333), it seems that a custom formatter can be added to the package.yaml file. Unfortunately, I've never done that before, and I'm wandering in the dark. I couldn't find a `hpack` option under [tests](https://github.com/sol/hpack#test-fields) that seemed appropriate. Maybe changing `type: exitcode-stdio-1.0`, but I don't know. Regardless, even if this is the option, I don't know an appropriate alternative.

**Comment by sunwukonga** [comment]
The reason for this is that I'd like to start offering bounties through [bountysource](bountysource.com) or similar, and to do that the problem domain needs to be well specified with meaningful (and visually distinct) tests that highlight the non-negotiable properties of a successful solution.

**Comment by jml** [comment]
This will do the trick:

```console
$ stack test --fast graphql-api
```

It won't run the tutorial tests or the graphql-wai tests though.

**Comment by sunwukonga** [comment]
I see, the `--fast` option turns off optimizations, and presumably one of those optimizations is to not print out the individualized test results.

Excellent! Thank you :)

**Comment by jml** [comment]
No, --fast works with colour too. The trick is to specify *which* stack
package is being built. Our stack.yaml has three, and if `stack test
--fast` is run *without* specifying a package, it will run all three in
parallel, and suppress output to avoid weird interleaving behaviour. If you
run a single package, it just executes the test suite normally.

**Comment by sunwukonga** [comment]
OK, now I've got it 👍
