### ISSUE TITLE
Drop generated cabal files from git tracking

### ISSUE THREAD

**Issue by sunwukonga** [jml/graphql-api#144]
Can I drop:
```
docs/source/tutorial/tutorial.cabal
graphql-wai/graphql-wai.cabal
```
from tracked and add them to `.gitignore` ?

**Comment by jml** [comment]
No strong objection. They are there for people who don’t want to use hpack
/ stack.

Why do you want to remove them?

**Comment by sunwukonga** [comment]
I use hpack and I haven't been commiting the cabal files because they are generated. I could have added them to commits, but it didn't feel right.

I see your point, some people may not be using hpack. Though if such a person were to contribute, it might be a problem when everyone else's stack automatically overwrites the new cabal files with config generated from the "then" out-of-date package.yaml.

**Comment by sunwukonga** [comment]
I'll commit the cabal files in future. It lowers the bar to entry into the code.
