### ISSUE TITLE
Sort out error handling

### ISSUE THREAD

**Issue by jml** [jml/graphql-api#20]
We're currently using `MonadThrow`, which throws in the base monad in `ExceptT` and thus might not be what we want.

Figure out something better to use.

**Comment by teh** [comment]
If we want to support partial success (optional, see "may" in quote below) then we're pretty constrained. The return type needs to be something like a tuple `([Error], Value)` so we can collect errors while building the return value.

From the spec:

> A response may contain both a partial response as well as encountered errors in the case that an error occurred on a field which was replaced with null.

**Comment by jml** [comment]
I think we do want to support it.

We might want to refine the type to be:

```haskell
data Result e a = OK a | Mixed e a |  Error e
```

We probably also want to emulate Servant and say that user's handlers run in the `ExceptT (Result e a) IO a` monad (perhaps giving a concrete type for `e`).

**Comment by jml** [comment]
I guess the reason a `Result` like I described would be useful is that it would let us define an algebra of how such results are combined.

**Comment by jml** [comment]
We should make a very clear distinction in our code between errors in the query (client-side errors, 400s) and errors in the definition (server-side, 500s) using a sum type. `panic` can happen at top-level runner function if necessary.
