### ISSUE TITLE
Set up readthedocs

### ISSUE THREAD

**Issue by jml** [jml/graphql-api#34]
I've created haskell-graphql-api.readthedocs.org.

Still to do:
- [x] Give @teh maintainer access (teh needs a readthedocs username)
- [ ] Add badge & link to README.md
- [x] Confirm that webhook actually works (NB: I didn't go for the automated process because I'm not comfortable giving other services admin access)

**Comment by teh** [comment]
Signup up to RTD as "teh" and donated a small amount to them.
