### ISSUE TITLE
Rename 'buildResolver'

### ISSUE THREAD

**Issue by jml** [jml/graphql-api#71]
Naming something to imply that it'll get used partially sometimes is not very Haskell.

e.g. it's `map`, not `buildMapper`. it's `filter`, not `buildFilterer`.

I suggest `execute` or `resolve`, or something similarly direct.

**Comment by teh** [comment]
maybe we should rename `HasGraph` to `HasResolver` as well? I think I prefer `resolve` because that's what most of the JS libraries are using. No need to be special for this particular name.

**Comment by teh** [comment]
(though `execute` would be fine as well of course, considering that the spec calls it "execution")

**Comment by jml** [comment]
+1 for `HasResolver` and `resolve`
